### ISSUE TITLE
Adding a new activity error - "name" is not allowed to be empty

### ISSUE THREAD

**Issue by nadavkav** [devlionco/moodle_mod_mindmaap#1]
Debug info:
Error code:
$a contents: Array
(
[status] =>
[message] => Validation Error
[errors] => Array
(
[0] => "name" is not allowed to be empty
)

)
×Stack trace:
line 74 of /mod/mindmaap/lib.php: moodle_exception thrown
line 122 of /course/modlib.php: call to mindmaap_add_instance()
line 154 of /course/modedit.php: call to add_moduleinfo()

**Comment by kirildevlion** [comment]
@nadavkav fixed

**Comment by kirildevlion** [comment]
@nadavkav fixed
